---
quorumFlags:
  privacy: false
  removeKeysOnDelete: false
  isBootnode: false    # Besu only, set this to true if this node is a bootnode
  usesBootnodes: false # Besu only, set this to true if the network you are connecting to use a bootnode/s that are deployed in the cluster

cluster:
  provider: local  # choose from: local | aws | azure
  cloudNativeServices: false # set to true to use Cloud Native Services (SecretsManager and IAM for AWS; KeyVault & Managed Identities for Azure)
  reclaimPolicy: Retain # set to either Retain or Delete; note that PVCs and PVs will still exist after a 'helm delete'. Setting to Retain will keep volumes even if PVCs/PVs are deleted in kubernetes. Setting to Delete will remove volumes from EC2 EBS when PVC is deleted

storage:
  sizeLimit: "50Gi"
  pvcSizeLimit: "50Gi"
  # NOTE: when you set this to Retain, the volume WILL persist after the chart is delete and you need to manually delete it
  reclaimPolicy: "Retain" # choose from: Delete | Retain 

node:
  env: prod
  labels:
    nodeType: ""
  goquorum:
    resources:
      cpuLimit: 1
      cpuRequest: 0.2
      memLimit: "5Gi"
      memRequest: "2Gi"
    # privKey:
    # pubKey:
    dataPath: "/data/quorum"
    keysPath: "/keys"
    genesisFilePath: "/etc/genesis/genesis.json"
    networkId: 1337
    replicaCount: 1
    account:
      unlock: 0
      password: 'password'
      passwordPath: "/keys/accountPassword"
    log:
      verbosity: 5
    miner:
      threads: 1
      blockPeriod: 5
    p2p:
      enabled: true
      addr: "0.0.0.0"
      port: 30303
    rpc:
      enabled: true
      addr: "0.0.0.0"
      port: 8545
      corsDomain: "*"
      vHosts: "*"
      api: "admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul"  
      authenticationEnabled: false
    ws:
      enabled: true
      addr: "0.0.0.0"
      port: 8546
      api: "admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul"
      origins: "*"
      authenticationEnabled: false
    graphql:
      enabled: true
      addr: "0.0.0.0"
      port: 8547
      corsDomain: "*"
      vHosts: "*"
    metrics:
      enabled: true
      pprofaddr: "0.0.0.0"
      pprofport: 9545
      serviceMonitorEnabled: true

image:
  goquorum:
    repository: quorumengineering/quorum
    tag: 22.7.1
  hooks:
    repository: consensys/quorum-k8s-hooks
    tag: qgt-0.2.3
    pullPolicy: IfNotPresent
